---
version: '3.4'

services:
  etherpad-app:
    build:
      context: ./etherpad_conf
      dockerfile: Dockerfile
    image: andri37/etherpad:v21.01.01
    ports: 
      - 8080:9001
    # volumes: {}

  postgres-app:
    build:
      context: ./postgres_conf
      dockerfile: Dockerfile
    image: postgres:13.4
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5555:8080
    volumes: 
      - database:/var/lib/postgresql/data
networks: {}
volumes: 
  - database: {}
  - etherdata: {}
